image:
  repository: asia-east2-docker.pkg.dev/dev-2026522/release-tracker/release-tracker-api
  tag: 8315f14

api:
  replicas: 2
  port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

postgres:
  image: postgres:16-alpine
  database: release_tracker
  user: postgres
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  storage: 5Gi

service:
  type: LoadBalancer
  port: 80
