apiVersion: v1
kind: Secret
metadata:
  name: release-tracker-secret
  namespace: release-tracker
  labels:
    {{- include "release-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: postgres
