apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sing-box

resources:
  - manifests/namespace.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml

secretGenerator:
  - name: sing-box-config
    files:
      - config.json=secrets/config.json