apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-api
  namespace: go-api
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: go-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s