apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-tracker-api
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - release-tracker
  selector:
    matchLabels:
      app.kubernetes.io/name: release-tracker
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
