{
 "title": "RED dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(go_api_http_request_duration_seconds_bucket[5m]))by(le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(go_api_http_requests_total{code=~\"5..\"}[5m]))/sum(rate(go_api_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(go_api_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}