apiVersion: v1
kind: Service
metadata:
  name: release-tracker-api
  namespace: release-tracker
spec:
  type: LoadBalancer
  selector:
    app: release-tracker-api
  ports:
    - port: 80
      targetPort: 8080
