replicaCount: 3
image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: 6.14.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  httpPort: 9898
probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi